-- Contrat de schéma utilisé par le harness RLS.
--
-- Cette version est alignée sur les types/colonnes réellement constatés sur le
-- projet Supabase GaspardNZ (PostgreSQL 17) au 2026-09-10. Elle reste minimale
-- (toutes les colonnes métier non nécessaires aux tests ne sont pas recopiées),
-- mais les TYPES et RELATIONS touchés par les migrations sont fidèles.

create type public.admin_role as enum ('owner','admin','editor','viewer');
create type public.lead_status as enum ('new','contacted','qualified','appointment','client','lost','archived');
create type public.booking_status as enum ('requested','confirmed','completed','cancelled','no_show');
create type public.email_status as enum ('queued','sent','delivered','opened','clicked','failed','bounced');
create type public.promotion_status as enum ('draft','scheduled','active','expired','archived');

create table public.admin_access (
  id uuid primary key default gen_random_uuid(),
  email text not null unique,
  role public.admin_role not null default 'viewer',
  display_name text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.visitors (
  id uuid primary key default gen_random_uuid(),
  last_seen_at timestamptz not null default now()
);
create table public.sessions (
  id uuid primary key default gen_random_uuid(),
  visitor_id uuid references public.visitors(id),
  started_at timestamptz not null default now()
);
create table public.analytics_events (
  id bigint generated by default as identity primary key,
  session_id uuid references public.sessions(id),
  visitor_id uuid references public.visitors(id),
  event_name text not null,
  created_at timestamptz not null default now()
);

create table public.leads (
  id uuid primary key default gen_random_uuid(),
  email text,
  full_name text,
  phone text,
  request_type text,
  message text,
  source text,
  status public.lead_status not null default 'new',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table public.customers (
  id uuid primary key default gen_random_uuid(),
  lead_id uuid references public.leads(id),
  email text,
  full_name text not null,
  phone text,
  source text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table public.bookings (
  id uuid primary key default gen_random_uuid(),
  lead_id uuid references public.leads(id),
  customer_id uuid references public.customers(id),
  provider text not null default 'calendly',
  status public.booking_status not null default 'requested',
  starts_at timestamptz,
  ends_at timestamptz,
  title text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table public.crm_notes (
  id uuid primary key default gen_random_uuid(),
  lead_id uuid references public.leads(id),
  customer_id uuid references public.customers(id),
  body text not null,
  created_by text,
  created_at timestamptz not null default now()
);
create table public.email_messages (
  id uuid primary key default gen_random_uuid(),
  lead_id uuid references public.leads(id),
  booking_id uuid references public.bookings(id),
  recipient text not null,
  subject text not null,
  status public.email_status not null default 'queued',
  queued_at timestamptz not null default now(),
  sent_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table public.email_events (
  id bigint generated by default as identity primary key,
  email_message_id uuid references public.email_messages(id),
  event_type text not null,
  created_at timestamptz not null default now()
);

create table public.site_settings (
  key text primary key,
  value jsonb not null default '{}'::jsonb,
  is_public boolean not null default true,
  description text,
  updated_by text,
  updated_at timestamptz not null default now()
);
create table public.site_content (
  id uuid primary key default gen_random_uuid(),
  section_key text not null,
  content_key text not null,
  locale text not null default 'fr',
  value jsonb not null default '{}'::jsonb,
  published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table public.content_albums (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  slug text not null,
  section_key text not null,
  published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table public.media_assets (
  id uuid primary key default gen_random_uuid(),
  section_key text not null,
  title text,
  public_url text not null,
  published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table public.news_posts (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  slug text not null,
  published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table public.packages (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null,
  published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table public.partners (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null,
  published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table public.partner_contacts (
  id uuid primary key default gen_random_uuid(),
  lead_id uuid references public.leads(id),
  full_name text not null,
  email text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table public.promotions (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  status public.promotion_status not null default 'draft',
  published boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table public.style_month (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table public.vip_clients (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table public.wedding_inspirations (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.integration_settings (
  provider text primary key,
  status text not null default 'disconnected',
  updated_at timestamptz not null default now()
);
create table public.integration_credentials (
  provider text primary key,
  access_token text,
  refresh_token text,
  updated_at timestamptz not null default now()
);
create table public.external_metric_snapshots (
  id bigint generated by default as identity primary key,
  provider text not null,
  metric_date date not null,
  dimension_key text not null default '',
  dimension_value text not null default '',
  metrics jsonb not null default '{}'::jsonb,
  fetched_at timestamptz not null default now()
);
create table public.oauth_states (
  state text primary key,
  provider text not null,
  admin_email text not null,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);
create table public.public_rate_limits (
  action text not null,
  key_hash text not null,
  bucket_start timestamptz not null,
  request_count integer not null default 0,
  primary key (action, key_hash, bucket_start)
);

create table public.activity_log (
  id bigint generated by default as identity primary key,
  event_type text not null,
  entity_type text,
  entity_id text,
  title text not null,
  description text,
  actor_email text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create table public.audit_log (
  id bigint generated by default as identity primary key,
  action text not null,
  actor_email text,
  before_data jsonb,
  after_data jsonb,
  entity_id text,
  entity_type text not null,
  created_at timestamptz not null default now()
);

-- Storage minimal, pour que le harness teste aussi le bucket site-media.
create schema if not exists storage;
grant usage on schema storage to anon, authenticated, service_role;
create table storage.objects (
  id uuid primary key default gen_random_uuid(),
  bucket_id text not null,
  name text not null
);

-- RLS activé comme en production.
do $$
declare t text;
begin
  foreach t in array array[
    'activity_log','admin_access','analytics_events','audit_log','bookings',
    'content_albums','crm_notes','customers','email_events','email_messages',
    'external_metric_snapshots','integration_credentials','integration_settings',
    'leads','media_assets','news_posts','oauth_states','packages','partner_contacts',
    'partners','promotions','public_rate_limits','sessions','site_content',
    'site_settings','style_month','vip_clients','visitors','wedding_inspirations'
  ] loop
    execute format('alter table public.%I enable row level security', t);
  end loop;
end $$;
alter table storage.objects enable row level security;

grant select, insert, update, delete on all tables in schema public to authenticated;
grant usage, select on all sequences in schema public to authenticated;
grant select, insert, update, delete on storage.objects to authenticated;
grant select on storage.objects to anon;

grant select on public.site_settings, public.site_content, public.content_albums,
  public.media_assets, public.news_posts, public.packages, public.partners,
  public.promotions, public.style_month, public.vip_clients,
  public.wedding_inspirations to anon;
